# Generated by Django 4.2.7 on 2023-11-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usertable',
        ),
    ]
